import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Alert, Dimensions,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';
import QRCode from 'react-native-qrcode-svg';
import {
  Camera,
  useCameraDevice,
  useCameraPermission,
  useCodeScanner,
} from 'react-native-vision-camera';

import { useTheme } from '@core/theme/ThemeProvider';
import { IdentityManager } from '@core/crypto/IdentityManager';
import { PreferencesStore, PREF_KEYS } from '@core/storage/preferences/PreferencesStore';
import { Container, DI_TOKENS } from '@core/di/Container';
import { EventBus } from '@core/events/EventBus';
import type { IGuardianRepository } from '../../domain/interfaces/IGuardianRepository';
import type { GuardianStackParams } from '@core/navigation/NavigationTypes';

type Nav   = NativeStackNavigationProp<GuardianStackParams, 'QRPair'>;
type Route = RouteProp<GuardianStackParams, 'QRPair'>;

/** QR payload exchanged between two GuardianCircle devices */
interface QRPayload {
  publicKey: string;
  encryptionPublicKey: string;
  fcmToken?: string;
  displayName: string;
  version: 2;
}

async function keyFingerprint(base64Key: string): Promise<string | null> {
  try {
    const bytes = Uint8Array.from(atob(base64Key), (c) => c.charCodeAt(0));
    const hashBuf = await globalThis.crypto.subtle.digest('SHA-256', bytes);
    const hex = Array.from(new Uint8Array(hashBuf))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    return hex.slice(0, 8).toUpperCase();
  } catch {
    return null;
  }
}

const SCREEN_SIZE = Dimensions.get('window').width * 0.72;

export default function QRPairScreen(): React.JSX.Element {
  const theme  = useTheme();
  const styles = makeStyles(theme);
  const nav    = useNavigation<Nav>();
  const route  = useRoute<Route>();
  const { mode, prefillName, prefillPhone } = route.params;

  // ── Show-mode state ────────────────────────────────────────────────────────
  const [myQRData, setMyQRData]   = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // ── Scan-mode state ────────────────────────────────────────────────────────
  const handledRef = useRef(false);   // prevent double-handling a single scan
  const { hasPermission, requestPermission } = useCameraPermission();
  const device = useCameraDevice('back');

  // ── Load own QR data ───────────────────────────────────────────────────────
  const loadMyQR = useCallback((): void => {
    setIsLoading(true);
    try {
      const pubKey = IdentityManager.getPublicKey();
      if (!pubKey) { throw new Error('Identity not initialised. Complete onboarding first.'); }
      const encPubKey = IdentityManager.getFCMPublicKey();
      const displayName =
        PreferencesStore.getString(PREF_KEYS.USER_DISPLAY_NAME) ?? 'GuardianCircle User';
      const payload: QRPayload = {
        publicKey: pubKey,
        encryptionPublicKey: encPubKey,
        displayName,
        version: 2,
      };
      setMyQRData(JSON.stringify(payload));
    } catch (err) {
      Alert.alert('Error', err instanceof Error ? err.message : 'Could not load identity.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (mode === 'show') { loadMyQR(); }
  }, [mode, loadMyQR]);

  // ── Request camera permission for scan mode ────────────────────────────────
  useEffect(() => {
    if (mode === 'scan' && !hasPermission) {
      void requestPermission();
    }
  }, [mode, hasPermission, requestPermission]);

  // ── Handle scanned QR ─────────────────────────────────────────────────────
  const handleScanned = useCallback(async (rawData: string): Promise<void> => {
    if (handledRef.current) { return; }
    handledRef.current = true;

    try {
      const payload = JSON.parse(rawData) as QRPayload;
      if (payload.version !== 2 || !payload.publicKey || !payload.encryptionPublicKey) {
        Alert.alert('Invalid QR Code', 'This QR code was not generated by GuardianCircle.', [
          { text: 'Try again', onPress: () => { handledRef.current = false; } },
        ]);
        return;
      }

      const repo = Container.resolve<IGuardianRepository>(DI_TOKENS.IGuardianRepository);
      const existing = await repo.findByPublicKey(payload.publicKey);
      const fp = await keyFingerprint(payload.publicKey);

      if (existing) {
        await repo.update(existing.id, {
          trustLevel: 2,
          fcmToken: payload.fcmToken,
          signingPublicKey: payload.publicKey,
          encryptionPublicKey: payload.encryptionPublicKey,
        });
        EventBus.emit('guardian:paired', { guardianId: existing.id });
        const fpLine = fp ? `\n\nKey fingerprint (verify with your guardian):\n${fp}` : '';
        Alert.alert(
          'Paired!',
          `${existing.displayName} is now a verified guardian (Level 2).${fpLine}`,
          [{ text: 'Done', onPress: () => nav.pop(2) }],
        );
      } else {
        const displayName = prefillName ?? payload.displayName;
        const phoneNumber = prefillPhone ?? '';
        const created = await repo.create({
          displayName,
          phoneNumber,
          signingPublicKey: payload.publicKey,
          encryptionPublicKey: payload.encryptionPublicKey,
          fcmToken: payload.fcmToken,
          trustLevel: 2,
          notificationPriority: 1,
          isActive: true,
          isDecoy: false,
          addedAt: new Date(),
        });
        EventBus.emit('guardian:added', { guardianId: created.id });
        EventBus.emit('guardian:paired', { guardianId: created.id });
        const fpLine = fp ? `\n\nKey fingerprint (verify with your guardian):\n${fp}` : '';
        Alert.alert(
          'Guardian Added',
          `${displayName} has been added as a verified guardian.${fpLine}`,
          [{ text: 'Done', onPress: () => nav.pop(2) }],
        );
      }
    } catch {
      Alert.alert('Error', 'Could not process this QR code.', [
        { text: 'Try again', onPress: () => { handledRef.current = false; } },
      ]);
    }
  }, [nav, prefillName, prefillPhone]);

  // ── Vision Camera code scanner ────────────────────────────────────────────
  const codeScanner = useCodeScanner({
    codeTypes: ['qr'],
    onCodeScanned: (codes) => {
      const value = codes[0]?.value;
      if (value) { void handleScanned(value); }
    },
  });

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <SafeAreaView style={styles.container} edges={['top', 'left', 'right']}>
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => nav.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
        >
          <Text style={[styles.back, { color: theme.colors.primary }]}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={[styles.title, { color: theme.colors.onBackground }]}>
          {mode === 'show' ? 'My QR Code' : 'Scan Guardian QR'}
        </Text>
        <View style={{ width: 64 }} />
      </View>

      <View style={styles.body}>
        {mode === 'show' ? (
          <>
            <Text style={[styles.instruction, { color: theme.colors.onSurfaceVariant }]}>
              Ask your guardian to scan this code with their GuardianCircle app.
            </Text>

            {isLoading ? (
              <ActivityIndicator color={theme.colors.primary} size="large" />
            ) : myQRData ? (
              <View style={[styles.qrBox, { backgroundColor: '#FFFFFF' }]}>
                <QRCode
                  value={myQRData}
                  size={SCREEN_SIZE}
                  color="#000000"
                  backgroundColor="#FFFFFF"
                />
              </View>
            ) : null}

            <Text style={[styles.levelNote, { color: theme.colors.onSurfaceVariant }]}>
              After scanning, both you and your guardian will be upgraded to{' '}
              <Text style={{ fontWeight: '700' }}>Verified (Level 2)</Text>, enabling
              end-to-end encrypted push notifications.
            </Text>
          </>
        ) : (
          <>
            <Text style={[styles.instruction, { color: theme.colors.onSurfaceVariant }]}>
              Point your camera at your guardian&apos;s QR code.
            </Text>

            {!hasPermission ? (
              <View style={[styles.cameraBox, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}>
                <Text style={[styles.cameraMsg, { color: theme.colors.onSurfaceVariant }]}>
                  Camera permission is required to scan QR codes.
                </Text>
                <TouchableOpacity
                  style={[styles.permBtn, { backgroundColor: theme.colors.primary }]}
                  onPress={() => { void requestPermission(); }}
                  accessibilityRole="button"
                >
                  <Text style={styles.permBtnText}>Grant Camera Access</Text>
                </TouchableOpacity>
              </View>
            ) : !device ? (
              <View style={[styles.cameraBox, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}>
                <Text style={[styles.cameraMsg, { color: theme.colors.onSurfaceVariant }]}>
                  No back camera found on this device.
                </Text>
              </View>
            ) : (
              <View style={[styles.cameraBox, { overflow: 'hidden', borderRadius: theme.radius.lg }]}>
                <Camera
                  style={StyleSheet.absoluteFill}
                  device={device}
                  isActive={true}
                  codeScanner={codeScanner}
                />
                {/* Corner markers */}
                <View style={styles.cornerTL} />
                <View style={styles.cornerTR} />
                <View style={styles.cornerBL} />
                <View style={styles.cornerBR} />
              </View>
            )}

            <Text style={[styles.levelNote, { color: theme.colors.onSurfaceVariant }]}>
              Make sure the QR code is well-lit and fits inside the viewfinder.
            </Text>
          </>
        )}
      </View>
    </SafeAreaView>
  );
}

const CAMERA_SIZE = Dimensions.get('window').width * 0.82;
const CORNER = 20;
const CORNER_THICKNESS = 3;

function makeStyles(theme: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.sm,
    },
    back: { fontSize: 17 },
    title: { ...theme.typography.titleMedium, flex: 1, textAlign: 'center' },
    body: { flex: 1, padding: theme.spacing.lg, alignItems: 'center', gap: theme.spacing.lg },
    instruction: { fontSize: 15, textAlign: 'center', lineHeight: 22 },
    qrBox: {
      padding: 16,
      borderRadius: theme.radius.lg,
      elevation: 2,
    },
    cameraBox: {
      width: CAMERA_SIZE,
      height: CAMERA_SIZE,
      borderRadius: theme.radius.lg,
      borderWidth: 1.5,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cameraMsg: { fontSize: 14, textAlign: 'center', paddingHorizontal: 24, marginBottom: 16 },
    permBtn: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: theme.radius.md,
    },
    permBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
    levelNote: { fontSize: 13, textAlign: 'center', lineHeight: 20, paddingHorizontal: theme.spacing.lg },
    // corner bracket markers overlay on camera view
    cornerTL: {
      position: 'absolute', top: 16, left: 16,
      width: CORNER, height: CORNER,
      borderTopWidth: CORNER_THICKNESS, borderLeftWidth: CORNER_THICKNESS, borderColor: '#FFFFFF',
      borderTopLeftRadius: 4,
    },
    cornerTR: {
      position: 'absolute', top: 16, right: 16,
      width: CORNER, height: CORNER,
      borderTopWidth: CORNER_THICKNESS, borderRightWidth: CORNER_THICKNESS, borderColor: '#FFFFFF',
      borderTopRightRadius: 4,
    },
    cornerBL: {
      position: 'absolute', bottom: 16, left: 16,
      width: CORNER, height: CORNER,
      borderBottomWidth: CORNER_THICKNESS, borderLeftWidth: CORNER_THICKNESS, borderColor: '#FFFFFF',
      borderBottomLeftRadius: 4,
    },
    cornerBR: {
      position: 'absolute', bottom: 16, right: 16,
      width: CORNER, height: CORNER,
      borderBottomWidth: CORNER_THICKNESS, borderRightWidth: CORNER_THICKNESS, borderColor: '#FFFFFF',
      borderBottomRightRadius: 4,
    },
  });
}
