import React, { useCallback, useEffect, useState } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';

import { useTheme } from '@core/theme/ThemeProvider';
import { IdentityManager } from '@core/crypto/IdentityManager';
import { Container, DI_TOKENS } from '@core/di/Container';
import { EventBus } from '@core/events/EventBus';
import type { IGuardianRepository } from '../../domain/interfaces/IGuardianRepository';
import type { GuardianStackParams } from '@core/navigation/NavigationTypes';

type Nav   = NativeStackNavigationProp<GuardianStackParams, 'QRPair'>;
type Route = RouteProp<GuardianStackParams, 'QRPair'>;

/**
 * Returns the first 8 hex chars of the SHA-256 of a base64-encoded public key,
 * or null if crypto.subtle is unavailable.
 * Shown after pairing for out-of-band MITM verification (Signal safety-number style).
 *
 * MUST return null on failure — never fall back to raw key bytes. All P-256 SPKI
 * keys share the same ASN.1 DER header, so base64Key.slice(0,8) is identical for
 * every user, rendering verification useless without any visible warning.
 */
async function keyFingerprint(base64Key: string): Promise<string | null> {
  try {
    const bytes = Uint8Array.from(atob(base64Key), (c) => c.charCodeAt(0));
    const hashBuf = await globalThis.crypto.subtle.digest('SHA-256', bytes);
    const hex = Array.from(new Uint8Array(hashBuf))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    return hex.slice(0, 8).toUpperCase();
  } catch {
    return null;
  }
}

/** QR payload exchanged between two GuardianCircle devices */
interface QRPayload {
  publicKey: string;           // ECDSA signing key (base64)
  encryptionPublicKey: string; // ECDH FCM encryption key (base64)
  fcmToken?: string;
  displayName: string;
  version: 2;
}

export default function QRPairScreen(): React.JSX.Element {
  const theme  = useTheme();
  const styles = makeStyles(theme);
  const nav    = useNavigation<Nav>();
  const route  = useRoute<Route>();
  const { mode } = route.params;

  const [myQRData, setMyQRData]   = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [scanResult, setScanResult] = useState<string | null>(null);

  const loadMyQR = useCallback(async () => {
    setIsLoading(true);
    try {
      // Build payload from own identity
      const pubKey = IdentityManager.getPublicKey();
      if (!pubKey) throw new Error('Identity not initialised. Complete onboarding first.');

      const encPubKey = IdentityManager.getFCMPublicKey();
      const displayName = 'GuardianCircle User'; // replaced with user preference in Phase 5
      const payload: QRPayload = {
        publicKey: pubKey,
        encryptionPublicKey: encPubKey,
        displayName,
        version: 2,
      };
      setMyQRData(JSON.stringify(payload));
    } catch (err) {
      Alert.alert('Error', err instanceof Error ? err.message : 'Could not load identity.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (mode === 'show') void loadMyQR();
  }, [mode, loadMyQR]);

  const handleScanned = async (rawData: string): Promise<void> => {
    setScanResult(rawData);
    try {
      const payload = JSON.parse(rawData) as QRPayload;
      if (payload.version !== 2 || !payload.publicKey || !payload.encryptionPublicKey) {
        Alert.alert('Invalid QR Code', 'This QR code was not generated by GuardianCircle.');
        setScanResult(null);
        return;
      }

      // Elevate guardian to trustLevel=2 if they already exist, else create
      const repo = Container.resolve<IGuardianRepository>(DI_TOKENS.IGuardianRepository);
      const existing = await repo.findByPublicKey(payload.publicKey);

      const fp = await keyFingerprint(payload.publicKey);

      if (existing) {
        await repo.update(existing.id, {
          trustLevel: 2,
          fcmToken: payload.fcmToken,
          signingPublicKey: payload.publicKey,
          encryptionPublicKey: payload.encryptionPublicKey,
        });
        EventBus.emit('guardian:paired', { guardianId: existing.id });
        const fpLine = fp
          ? `\n\nVerify with your guardian that their key fingerprint matches:\n${fp}`
          : '';
        Alert.alert(
          'Paired!',
          `${existing.displayName} is now a verified guardian (Level 2).${fpLine}`,
          [{ text: 'Done', onPress: () => nav.pop(2) }],
        );
      } else {
        // Guardian scanned us first — create them at trustLevel=2
        const created = await repo.create({
          displayName: payload.displayName,
          phoneNumber: '',
          signingPublicKey: payload.publicKey,
          encryptionPublicKey: payload.encryptionPublicKey,
          fcmToken: payload.fcmToken,
          trustLevel: 2,
          notificationPriority: 1,
          isActive: true,
          isDecoy: false,
          addedAt: new Date(),
        });
        EventBus.emit('guardian:added', { guardianId: created.id });
        EventBus.emit('guardian:paired', { guardianId: created.id });
        const fpLine = fp
          ? `\n\nVerify with them that their key fingerprint matches:\n${fp}`
          : '';
        Alert.alert(
          'Guardian Added',
          `${payload.displayName} has been added as a verified guardian.${fpLine}\n\nYou can add their phone number from the guardians list.`,
          [{ text: 'Done', onPress: () => nav.pop(2) }],
        );
      }
    } catch {
      Alert.alert('Error', 'Could not process this QR code. Ensure both devices are using GuardianCircle.');
      setScanResult(null);
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['top', 'left', 'right']}>
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => nav.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
        >
          <Text style={[styles.back, { color: theme.colors.primary }]}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={[styles.title, { color: theme.colors.onBackground }]}>
          {mode === 'show' ? 'My QR Code' : 'Scan Guardian QR'}
        </Text>
        <View style={{ width: 64 }} />
      </View>

      <View style={styles.body}>
        {mode === 'show' ? (
          <>
            <Text style={[styles.instruction, { color: theme.colors.onSurfaceVariant }]}>
              Ask your guardian to scan this code using their GuardianCircle app.
            </Text>

            {isLoading ? (
              <ActivityIndicator color={theme.colors.primary} size="large" />
            ) : myQRData ? (
              <View style={[styles.qrPlaceholder, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}>
                {/* Real QR rendering requires react-native-qrcode-svg — placeholder until Phase 4 */}
                <Text style={[styles.qrPlaceholderText, { color: theme.colors.onSurfaceVariant }]}>
                  QR Code
                </Text>
                <Text style={[styles.qrNote, { color: theme.colors.onSurfaceVariant }]}>
                  (requires react-native-qrcode-svg — add in Phase 4)
                </Text>
                <Text
                  style={[styles.qrRaw, { color: theme.colors.onSurfaceVariant }]}
                  numberOfLines={3}
                  ellipsizeMode="middle"
                >
                  {myQRData}
                </Text>
              </View>
            ) : null}

            <Text style={[styles.levelNote, { color: theme.colors.onSurfaceVariant }]}>
              After scanning, both you and your guardian will be upgraded to{' '}
              <Text style={{ fontWeight: '700' }}>Verified (Level 2)</Text>, enabling
              end-to-end encrypted push notifications.
            </Text>
          </>
        ) : (
          <>
            <Text style={[styles.instruction, { color: theme.colors.onSurfaceVariant }]}>
              Point your camera at the guardian&apos;s QR code.
            </Text>

            <View style={[styles.qrPlaceholder, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}>
              <Text style={[styles.qrPlaceholderText, { color: theme.colors.onSurfaceVariant }]}>
                Camera view
              </Text>
              <Text style={[styles.qrNote, { color: theme.colors.onSurfaceVariant }]}>
                (requires react-native-vision-camera — add in Phase 4)
              </Text>
            </View>

            {/* Dev-mode: manual paste for testing */}
            <TouchableOpacity
              style={[styles.devBtn, { borderColor: theme.colors.border }]}
              onPress={() => {
                const ts = Date.now();
                const test: QRPayload = { publicKey: 'test_signing_' + ts, encryptionPublicKey: 'test_ecdh_' + ts, displayName: 'Test Guardian', version: 2 };
                void handleScanned(JSON.stringify(test));
              }}
              accessibilityRole="button"
            >
              <Text style={[styles.devBtnText, { color: theme.colors.onSurfaceVariant }]}>
                [Dev] Simulate scan
              </Text>
            </TouchableOpacity>

            {scanResult && (
              <Text style={[styles.scanResult, { color: theme.colors.onSurface }]}>
                Scanned: {scanResult.slice(0, 60)}…
              </Text>
            )}
          </>
        )}
      </View>
    </SafeAreaView>
  );
}

function makeStyles(theme: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.lg, paddingTop: theme.spacing.md, paddingBottom: theme.spacing.sm,
    },
    back: { fontSize: 17 },
    title: { ...theme.typography.titleMedium, flex: 1, textAlign: 'center' },
    body: { flex: 1, padding: theme.spacing.lg, alignItems: 'center' },
    instruction: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: theme.spacing.xl },
    qrPlaceholder: {
      width: 240, height: 240, borderRadius: theme.radius.lg,
      borderWidth: 1.5, alignItems: 'center', justifyContent: 'center',
      marginBottom: theme.spacing.lg,
    },
    qrPlaceholderText: { fontSize: 16, fontWeight: '600', marginBottom: 8 },
    qrNote: { fontSize: 12, textAlign: 'center', paddingHorizontal: 16 },
    qrRaw: { fontSize: 10, textAlign: 'center', paddingHorizontal: 12, marginTop: 8 },
    levelNote: { fontSize: 13, textAlign: 'center', lineHeight: 20, paddingHorizontal: theme.spacing.lg },
    devBtn: {
      borderWidth: 1, borderRadius: theme.radius.md,
      paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm,
      marginTop: theme.spacing.lg,
    },
    devBtnText: { fontSize: 13 },
    scanResult: { fontSize: 11, marginTop: 8, textAlign: 'center' },
  });
}
